import { Injectable } from '@nestjs/common';
import fs from 'fs/promises';
import path from 'path';
import { OPENCLAW_STATE_DIR } from './config.js';

type ResearchKeyName = 'tavilyApiKey' | 'exaApiKey' | 'firecrawlApiKey' | 'openaiEmbeddingApiKey';

interface ResearchKeysFile {
  tavilyApiKey?: string;
  exaApiKey?: string;
  firecrawlApiKey?: string;
  openaiEmbeddingApiKey?: string;
  updatedAt?: string;
}

export interface ResearchKeysStatus {
  tavilyApiKey: { configured: boolean };
  exaApiKey: { configured: boolean };
  firecrawlApiKey: { configured: boolean };
  openaiEmbeddingApiKey: { configured: boolean };
  updatedAt: string | null;
}

export interface UpdateResearchKeysInput {
  tavilyApiKey?: string | null;
  exaApiKey?: string | null;
  firecrawlApiKey?: string | null;
  openaiEmbeddingApiKey?: string | null;
}

const CONFIG_DIR = path.join(OPENCLAW_STATE_DIR, 'workspace', 'report-agent', 'config');
const KEYS_JSON_PATH = path.join(CONFIG_DIR, 'research-keys.json');
const KEYS_ENV_PATH = path.join(CONFIG_DIR, 'research-keys.env');

const ENV_NAMES: Record<ResearchKeyName, string> = {
  tavilyApiKey: 'TAVILY_API_KEY',
  exaApiKey: 'EXA_API_KEY',
  firecrawlApiKey: 'FIRECRAWL_API_KEY',
  openaiEmbeddingApiKey: 'OPENAI_API_KEY',
};

@Injectable()
export class ResearchKeysService {
  async getStatus(): Promise<ResearchKeysStatus> {
    return this.toStatus(await this.readKeys());
  }

  async updateKeys(input: UpdateResearchKeysInput): Promise<ResearchKeysStatus> {
    const current = await this.readKeys();
    const next: ResearchKeysFile = { ...current };
    let changed = false;

    for (const key of Object.keys(ENV_NAMES) as ResearchKeyName[]) {
      if (!Object.prototype.hasOwnProperty.call(input, key)) continue;
      const value = input[key];
      if (value === null) {
        if (next[key]) changed = true;
        delete next[key];
      } else if (typeof value === 'string') {
        const trimmed = value.trim();
        if (trimmed) {
          if (next[key] !== trimmed) changed = true;
          next[key] = trimmed;
        }
      }
    }

    if (changed) next.updatedAt = new Date().toISOString();
    await this.writeKeys(next);
    return this.toStatus(next);
  }

  async getEffectiveKey(name: ResearchKeyName): Promise<string> {
    const keys = await this.readKeys();
    return keys[name] || process.env[ENV_NAMES[name]] || '';
  }

  private async readKeys(): Promise<ResearchKeysFile> {
    try {
      const raw = await fs.readFile(KEYS_JSON_PATH, 'utf-8');
      const parsed = JSON.parse(raw) as ResearchKeysFile;
      return parsed && typeof parsed === 'object' ? parsed : {};
    } catch {
      return {};
    }
  }

  private async writeKeys(keys: ResearchKeysFile): Promise<void> {
    await fs.mkdir(CONFIG_DIR, { recursive: true });
    await fs.writeFile(KEYS_JSON_PATH, JSON.stringify(keys, null, 2), { encoding: 'utf-8', mode: 0o600 });
    await fs.writeFile(KEYS_ENV_PATH, this.toEnvFile(keys), { encoding: 'utf-8', mode: 0o600 });
    await Promise.allSettled([fs.chmod(KEYS_JSON_PATH, 0o600), fs.chmod(KEYS_ENV_PATH, 0o600)]);
  }

  private toEnvFile(keys: ResearchKeysFile): string {
    const lines = ['# Generated by gaogao-api. Do not commit this file.'];
    for (const key of Object.keys(ENV_NAMES) as ResearchKeyName[]) {
      const value = keys[key];
      if (value) lines.push(`export ${ENV_NAMES[key]}=${this.shellQuote(value)}`);
    }
    return `${lines.join('\n')}\n`;
  }

  private shellQuote(value: string): string {
    return `'${value.replace(/'/g, `'\\''`)}'`;
  }

  private toStatus(keys: ResearchKeysFile): ResearchKeysStatus {
    return {
      tavilyApiKey: { configured: Boolean(keys.tavilyApiKey) },
      exaApiKey: { configured: Boolean(keys.exaApiKey) },
      firecrawlApiKey: { configured: Boolean(keys.firecrawlApiKey) },
      openaiEmbeddingApiKey: { configured: Boolean(keys.openaiEmbeddingApiKey || process.env.OPENAI_API_KEY) },
      updatedAt: keys.updatedAt || null,
    };
  }
}
